spring:
  datasource:
    url: jdbc:mysql://localhost/db_wechat?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

mybatis:
  type-aliases-package: com.chen.wechat.model
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
    - com.chen.wechat.common.BaseMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 8081
  servlet:
    context-path: /wechat